name: Helm Publisher

on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Helm Publisher
      uses: stefanprodan/helm-gh-pages@v1.0.0
      with:
        token: ${{ secrets.MY_TOKEN }}
        charts_dir: .
        charts_url: https://www.koslib.com/mycharts
        owner: koslibpro
        repository: mycharts
